# Dockerfile.rails
ARG RUBY_VERSION=3.3
FROM ruby:${RUBY_VERSION} AS rails-toolbox

ENV INSTALL_PATH "/app"
ENV INSTALL_PATH /app
# Install rails and create directory
RUN mkdir -p $INSTALL_PATH && gem install rails bundler

# Run a shell
CMD ["/bin/sh"]
