# Dockerfile.rails
ARG RUBY_VERSION=3.3
FROM ruby:${RUBY_VERSION} AS dockerails

# Default directory
ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH

# Install rails
RUN gem install rails bundler
#RUN chown -R app:app /app
WORKDIR /app

# Run a shell
CMD ["/bin/sh"]
